# Generated by Django 6.0.2 on 2026-02-22 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        ('qa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAChecklistForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('area_inspected', models.CharField(help_text='Location / area inspected', max_length=200)),
                ('workmanship_quality', models.CharField(choices=[('pass', 'Pass'), ('minor', 'Minor Issue'), ('major', 'Major Issue'), ('fail', 'Fail'), ('na', 'N/A')], default='pass', max_length=10)),
                ('workmanship_notes', models.TextField(blank=True)),
                ('materials_correct', models.BooleanField(default=True, help_text='Correct materials used as per specification')),
                ('materials_stored_properly', models.BooleanField(default=True)),
                ('materials_notes', models.TextField(blank=True)),
                ('work_to_method_statement', models.BooleanField(default=True, help_text='Work carried out as per method statement')),
                ('work_to_drawings', models.BooleanField(default=True, help_text='Work carried out as per drawings')),
                ('deviations', models.TextField(blank=True, help_text='List any deviations from method statement or drawings')),
                ('area_clean_tidy', models.BooleanField(default=True, help_text='Work area clean and tidy')),
                ('waste_segregated', models.BooleanField(default=True, help_text='Waste properly segregated')),
                ('barriers_signage', models.BooleanField(default=True, help_text='Barriers and signage in place')),
                ('ppe_compliant', models.BooleanField(default=True, help_text='All personnel wearing correct PPE')),
                ('housekeeping_notes', models.TextField(blank=True)),
                ('existing_services_protected', models.BooleanField(default=True, help_text='Existing services protected from damage')),
                ('completed_work_protected', models.BooleanField(default=True, help_text='Completed work protected')),
                ('protection_notes', models.TextField(blank=True)),
                ('snags_identified', models.TextField(blank=True, help_text='List of defects/snags found')),
                ('snags_count', models.IntegerField(default=0)),
                ('overall_outcome', models.CharField(choices=[('approved', 'Approved'), ('conditional', 'Conditional Approval'), ('rework', 'Rework Required'), ('rejected', 'Rejected')], default='approved', max_length=15)),
                ('inspector_comments', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_details', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_checklists', to='projects.project')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_forms', to='core.team')),
            ],
            options={
                'ordering': ['-shift_date', 'team__code'],
                'unique_together': {('team', 'shift_date', 'area_inspected')},
            },
        ),
    ]
