# Generated by Django 6.0.2 on 2026-02-22 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=15)),
                ('total_teams', models.IntegerField(default=0)),
                ('briefing_forms_submitted', models.IntegerField(default=0)),
                ('qa_forms_submitted', models.IntegerField(default=0)),
                ('total_staff_present', models.IntegerField(default=0)),
                ('total_staff_expected', models.IntegerField(default=0)),
                ('incidents_count', models.IntegerField(default=0)),
                ('overall_risk', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=10)),
                ('manager_summary', models.TextField(blank=True, help_text='Night Operations Manager summary')),
                ('key_issues', models.TextField(blank=True)),
                ('handover_notes', models.TextField(blank=True, help_text='Notes for the day shift')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
