# Generated by Django 6.0.2 on 2026-02-21 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('task_started', 'Task Started'), ('task_completed', 'Task Completed'), ('break_start', 'Break Started'), ('break_end', 'Break Ended'), ('incident', 'Incident Reported'), ('update', 'Status Update'), ('handover', 'Shift Handover'), ('delay', 'Delay Reported')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('near_miss', 'Near Miss'), ('minor', 'Minor'), ('major', 'Major'), ('serious', 'Serious')], max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('immediate_action', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.team')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_task', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_break', 'On Break'), ('standby', 'Standby'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('incident', 'Incident')], default='active', max_length=20)),
                ('staff_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.team')),
            ],
            options={
                'verbose_name_plural': 'Team Statuses',
                'ordering': ['team__code'],
            },
        ),
    ]
