# Generated by Django 6.0.2 on 2026-02-21 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NightBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('shift', models.CharField(default='night', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('total_staff_present', models.IntegerField(default=0)),
                ('total_staff_expected', models.IntegerField(default=0)),
                ('safety_briefing', models.TextField(blank=True, help_text='Safety topics discussed')),
                ('key_decisions', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('escalations', models.TextField(blank=True, help_text='Issues escalated to management')),
                ('next_shift_handover', models.TextField(blank=True)),
                ('overall_risk', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='green', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BriefingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='briefing.nightbriefing')),
            ],
        ),
        migrations.CreateModel(
            name='PreBriefingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('staff_present', models.IntegerField(default=0)),
                ('staff_expected', models.IntegerField(default=0)),
                ('absentees', models.TextField(blank=True, help_text='List absentees and reasons')),
                ('equipment_status', models.CharField(choices=[('all_ok', 'All OK'), ('minor_issues', 'Minor Issues'), ('major_issues', 'Major Issues'), ('critical', 'Critical')], default='all_ok', max_length=20)),
                ('equipment_notes', models.TextField(blank=True)),
                ('ppe_check_completed', models.BooleanField(default=False)),
                ('safety_concerns', models.TextField(blank=True)),
                ('near_misses', models.TextField(blank=True, help_text='Report any near misses from previous shift')),
                ('pending_tasks_from_previous', models.TextField(blank=True, help_text='Tasks carried over from previous shift')),
                ('planned_tasks_tonight', models.TextField(blank=True, help_text='What the team plans to accomplish')),
                ('blockers', models.TextField(blank=True, help_text='Any blockers or dependencies')),
                ('materials_needed', models.TextField(blank=True)),
                ('permits_in_place', models.BooleanField(default=True)),
                ('permit_details', models.TextField(blank=True)),
                ('method_statements_reviewed', models.BooleanField(default=False)),
                ('weather_impact', models.CharField(choices=[('none', 'No Impact'), ('minor', 'Minor Impact'), ('significant', 'Significant Impact'), ('work_stopped', 'Work Stopped')], default='none', max_length=20)),
                ('weather_notes', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('risk_rating', models.CharField(choices=[('green', 'Green - Low Risk'), ('amber', 'Amber - Medium Risk'), ('red', 'Red - High Risk')], default='green', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prebriefing_forms', to='core.team')),
            ],
            options={
                'ordering': ['-shift_date', 'team__code'],
                'unique_together': {('team', 'shift_date')},
            },
        ),
    ]
